// SPDX-License-Identifier: GPL-2.0-only
// Copyright (C) 2026 George Kottler <mail@kottlerg.com>

// kernel/src/entropy/cpurng.rs

//! Per-CPU CSPRNG.
//!
//! One forward-secure generator per CPU, reseeded from the central pool. Each
//! instance is touched only by its owning CPU under interrupt-disabled
//! exclusivity (see the draw API in [`super`]), so it needs no lock.
//!
//! Reseed policy lives in [`super::reseed_policy`]: mandatory reseeds
//! (first use, VMGENID generation change, overdue time budget) block on the
//! pool lock; opportunistic reseeds (draw interval, time budget) use the
//! non-spinning pool path and defer one draw under contention. Each reseed
//! folds any accumulated per-CPU jitter into the pool, draws fresh seed
//! material, and absorbs it. Forward secrecy across draws is provided by the
//! sponge's per-fill erasure.

use super::reseed_policy::{self, Action};
use super::sponge::Prng;
use super::{jitter, pool, vmgenid};

/// Seed material drawn per reseed (256-bit reseed).
const RESEED_BYTES: usize = 32;

/// A per-CPU generator plus its reseed bookkeeping.
pub struct CpuRng
{
    prng: Prng,
    draws_since_reseed: u64,
    seeded: bool,
    /// VMGENID GUID this generator last reseeded under; a live mismatch means
    /// the whole VM (this generator included) may be a replayed snapshot.
    /// Zero when the platform has no VMGENID.
    guid_seen: [u8; 16],
    /// `elapsed_us` timestamp of the last successful reseed (0 = none/uncalibrated).
    last_reseed_us: u64,
}

impl CpuRng
{
    /// A zero-initialized generator (matches a zeroed slab slot).
    pub const fn new() -> Self
    {
        Self {
            prng: Prng::new(),
            draws_since_reseed: 0,
            seeded: false,
            guid_seen: [0; 16],
            last_reseed_us: 0,
        }
    }

    /// Force a mandatory reseed on the next fill. Used after the boot
    /// self-test capture, whose draw seeds the generator from the
    /// scrape-dominated boot-time pool: the first consumer draw then reseeds
    /// with the runtime jitter accrued in between.
    pub fn mark_stale(&mut self)
    {
        self.seeded = false;
    }

    /// Blocking reseed: fold jitter, absorb the live GUID (so post-resume
    /// output diverges across clones even under identical jitter), draw and
    /// absorb fresh seed material.
    fn reseed_mandatory(&mut self, cpu: usize, guid: Option<[u8; 16]>, now_us: u64)
    {
        jitter::contribute_to_pool(cpu);
        if let Some(g) = guid
        {
            pool::absorb(&g);
        }
        let mut seed = [0u8; RESEED_BYTES];
        pool::draw_seed(&mut seed);
        self.prng.absorb(&seed);
        seed.fill(0);
        self.finish_reseed(guid, now_us);
    }

    /// Non-spinning reseed; `false` = pool lock contended, nothing changed —
    /// the caller draws from current state and retries next draw.
    fn try_reseed(&mut self, cpu: usize, guid: Option<[u8; 16]>, now_us: u64) -> bool
    {
        if !jitter::try_contribute_to_pool(cpu)
        {
            return false;
        }
        let mut seed = [0u8; RESEED_BYTES];
        if !pool::try_draw_seed(&mut seed)
        {
            return false;
        }
        self.prng.absorb(&seed);
        seed.fill(0);
        self.finish_reseed(guid, now_us);
        true
    }

    fn finish_reseed(&mut self, guid: Option<[u8; 16]>, now_us: u64)
    {
        if let Some(g) = guid
        {
            self.guid_seen = g;
        }
        self.last_reseed_us = now_us;
        self.draws_since_reseed = 0;
        self.seeded = true;
    }

    /// Fill `out` with generated bytes, reseeding per policy first.
    pub fn fill(&mut self, cpu: usize, out: &mut [u8])
    {
        let guid = vmgenid::read_guid();
        let guid_changed = matches!(guid, Some(g) if g != self.guid_seen);
        let now_us = crate::arch::current::timer::elapsed_us().unwrap_or(0);
        match reseed_policy::decide(
            self.seeded,
            guid_changed,
            self.draws_since_reseed,
            now_us,
            self.last_reseed_us,
        )
        {
            Action::Mandatory => self.reseed_mandatory(cpu, guid, now_us),
            Action::Opportunistic =>
            {
                let _ = self.try_reseed(cpu, guid, now_us);
            }
            Action::None =>
            {}
        }
        self.prng.fill(out);
        self.draws_since_reseed = self.draws_since_reseed.saturating_add(1);
    }
}
