// SPDX-License-Identifier: GPL-2.0-only
// Copyright (C) 2026 George Kottler <mail@kottlerg.com>

// kernel/src/entropy/cpurng.rs

//! Per-CPU CSPRNG.
//!
//! One forward-secure generator per CPU, reseeded from the central pool. Each
//! instance is touched only by its owning CPU under interrupt-disabled
//! exclusivity (see the draw API in [`super`]), so it needs no lock.
//!
//! Reseed policy: a generator reseeds on first use and then every
//! [`RESEED_DRAW_INTERVAL`] draws. Each reseed folds any accumulated per-CPU
//! jitter into the pool, draws fresh seed material, and absorbs it. Forward
//! secrecy across draws is provided by the sponge's per-fill erasure.

use super::sponge::Prng;
use super::{jitter, pool};

/// Seed material drawn per reseed (256-bit reseed).
const RESEED_BYTES: usize = 32;

/// Draws between reseeds. Bounds how much output depends on any single seed
/// without making reseeding (a pool lock + permutations) a per-draw cost.
const RESEED_DRAW_INTERVAL: u64 = 256;

/// A per-CPU generator plus its reseed bookkeeping.
pub struct CpuRng
{
    prng: Prng,
    draws_since_reseed: u64,
    seeded: bool,
}

impl CpuRng
{
    /// A zero-initialized generator (matches a zeroed slab slot).
    pub const fn new() -> Self
    {
        Self {
            prng: Prng::new(),
            draws_since_reseed: 0,
            seeded: false,
        }
    }

    /// Fold this CPU's jitter into the pool, draw fresh seed, and absorb it.
    pub fn reseed(&mut self, cpu: usize)
    {
        jitter::contribute_to_pool(cpu);
        let mut seed = [0u8; RESEED_BYTES];
        pool::draw_seed(&mut seed);
        self.prng.absorb(&seed);
        seed.fill(0);
        self.draws_since_reseed = 0;
        self.seeded = true;
    }

    /// Fill `out` with generated bytes, reseeding per policy first.
    pub fn fill(&mut self, cpu: usize, out: &mut [u8])
    {
        if !self.seeded || self.draws_since_reseed >= RESEED_DRAW_INTERVAL
        {
            self.reseed(cpu);
        }
        self.prng.fill(out);
        self.draws_since_reseed = self.draws_since_reseed.saturating_add(1);
    }
}
