// SPDX-License-Identifier: GPL-2.0-only
// Copyright (C) 2026 George Kottler <mail@kottlerg.com>

// kernel/src/entropy/sponge.rs

//! Forward-secure duplex PRNG over Keccak-f[1600].
//!
//! [`Prng`] is a sponge in duplex mode: [`Prng::absorb`] injects entropy by
//! folding it into the rate and permuting; [`Prng::fill`] squeezes output and
//! then erases it for forward secrecy. The 512-bit capacity (never output) is
//! the perpetual secret that carries state forward, giving 256-bit security.
//!
//! Forward secrecy (fast key erasure): after squeezing, [`Prng::fill`] zeroes
//! the just-exposed rate region and permutes once more. The permutation is
//! invertible, so the extra permute alone would not hide the output — zeroing
//! the rate first is what makes the returned bytes unrecoverable from the
//! post-fill state. A later full-state compromise therefore cannot reproduce
//! previously drawn bytes.

use super::keccak::{LANES, keccak_f1600};

/// Sponge rate in bytes (SHAKE256: 1088-bit rate, 512-bit capacity).
pub const RATE: usize = 136;

/// Number of fully-rate lanes (`RATE / 8`).
const RATE_LANES: usize = RATE / 8;

/// XOR up to [`RATE`] bytes of `block` into the rate region (little-endian).
fn absorb_into(st: &mut [u64; LANES], block: &[u8])
{
    debug_assert!(block.len() <= RATE);
    let mut i = 0;
    while i < block.len()
    {
        let mut lane = st[i / 8].to_le_bytes();
        let take = core::cmp::min(8, block.len() - i);
        for k in 0..take
        {
            lane[k] ^= block[i + k];
        }
        st[i / 8] = u64::from_le_bytes(lane);
        i += take;
    }
}

/// Read up to [`RATE`] bytes from the rate region (little-endian) into `out`.
fn squeeze_from(st: &[u64; LANES], out: &mut [u8])
{
    debug_assert!(out.len() <= RATE);
    let mut i = 0;
    while i < out.len()
    {
        let lane = st[i / 8].to_le_bytes();
        let take = core::cmp::min(8, out.len() - i);
        out[i..i + take].copy_from_slice(&lane[..take]);
        i += take;
    }
}

/// Zero the rate region, leaving the capacity untouched.
fn zero_rate(st: &mut [u64; LANES])
{
    for lane in st.iter_mut().take(RATE_LANES)
    {
        *lane = 0;
    }
}

/// A forward-secure duplex PRNG.
pub struct Prng
{
    st: [u64; LANES],
}

impl Prng
{
    /// A zero-initialized generator. Useless until seeded via [`Prng::absorb`].
    pub const fn new() -> Self
    {
        Self { st: [0; LANES] }
    }

    /// Inject `data` into the state (duplex absorb). Used for seeding and
    /// reseeding; safe to call repeatedly with new entropy.
    pub fn absorb(&mut self, data: &[u8])
    {
        let mut off = 0;
        while off < data.len()
        {
            let n = core::cmp::min(RATE, data.len() - off);
            absorb_into(&mut self.st, &data[off..off + n]);
            keccak_f1600(&mut self.st);
            off += n;
        }
    }

    /// Fill `out` with generated bytes, then erase them from the state.
    pub fn fill(&mut self, out: &mut [u8])
    {
        let mut off = 0;
        while off < out.len()
        {
            keccak_f1600(&mut self.st);
            let n = core::cmp::min(RATE, out.len() - off);
            squeeze_from(&self.st, &mut out[off..off + n]);
            off += n;
        }
        // Forward secrecy: erase the exposed rate, then ratchet.
        zero_rate(&mut self.st);
        keccak_f1600(&mut self.st);
    }

    /// Test-only view of the raw state, for the erasure property test.
    #[cfg(test)]
    fn raw_state(&self) -> [u64; LANES]
    {
        self.st
    }
}

#[cfg(test)]
mod tests
{
    use super::*;

    /// One-shot SHAKE256 (FIPS 202) over the shared absorb/squeeze plumbing,
    /// used only to anchor that plumbing against the NIST known-answer vector.
    fn shake256(input: &[u8], out: &mut [u8])
    {
        let mut st = [0u64; LANES];
        let mut off = 0;
        while input.len() - off >= RATE
        {
            absorb_into(&mut st, &input[off..off + RATE]);
            keccak_f1600(&mut st);
            off += RATE;
        }
        let rem = input.len() - off;
        let mut last = [0u8; RATE];
        last[..rem].copy_from_slice(&input[off..]);
        last[rem] |= 0x1F;
        last[RATE - 1] |= 0x80;
        absorb_into(&mut st, &last);
        keccak_f1600(&mut st);

        let mut o = 0;
        loop
        {
            let take = core::cmp::min(RATE, out.len() - o);
            squeeze_from(&st, &mut out[o..o + take]);
            o += take;
            if o >= out.len()
            {
                break;
            }
            keccak_f1600(&mut st);
        }
    }

    /// `SHAKE256("")`, first 32 bytes — the canonical NIST FIPS 202 vector.
    #[test]
    fn shake256_empty_kat()
    {
        let mut out = [0u8; 32];
        shake256(&[], &mut out);
        let expected: [u8; 32] = [
            0x46, 0xb9, 0xdd, 0x2b, 0x0b, 0xa8, 0x8d, 0x13, 0x23, 0x3b, 0x3f, 0xeb, 0x74, 0x3e,
            0xeb, 0x24, 0x3f, 0xcd, 0x52, 0xea, 0x62, 0xb8, 0x1b, 0x82, 0xb5, 0x0c, 0x27, 0x64,
            0x6e, 0xd5, 0x76, 0x2f,
        ];
        assert_eq!(out, expected);
    }

    /// `SHAKE256` output longer than one rate block stays consistent with a
    /// prefix request (the squeeze loop spans blocks correctly).
    #[test]
    fn shake256_spans_blocks()
    {
        let mut short = [0u8; 32];
        let mut long = [0u8; 200];
        shake256(b"seraph", &mut short);
        shake256(b"seraph", &mut long);
        assert_eq!(&long[..32], &short[..]);
        assert!(long[136..].iter().any(|&b| b != 0));
    }

    /// Same seed → same stream; different seed → different stream.
    #[test]
    fn deterministic_and_seed_sensitive()
    {
        let mut a = Prng::new();
        let mut b = Prng::new();
        a.absorb(b"seed-A");
        b.absorb(b"seed-A");
        let (mut oa, mut ob) = ([0u8; 64], [0u8; 64]);
        a.fill(&mut oa);
        b.fill(&mut ob);
        assert_eq!(oa, ob);

        let mut c = Prng::new();
        c.absorb(b"seed-B");
        let mut oc = [0u8; 64];
        c.fill(&mut oc);
        assert_ne!(oa, oc);
    }

    /// Consecutive fills do not repeat.
    #[test]
    fn fills_advance()
    {
        let mut p = Prng::new();
        p.absorb(b"seed");
        let (mut x, mut y) = ([0u8; 64], [0u8; 64]);
        p.fill(&mut x);
        p.fill(&mut y);
        assert_ne!(x, y);
    }

    /// Forward-secrecy erasure: the rate region of the post-fill state does not
    /// contain the bytes just returned (the zero-rate ratchet ran).
    #[test]
    fn erases_output_from_state()
    {
        let mut p = Prng::new();
        p.absorb(b"seed");
        let mut out = [0u8; RATE];
        p.fill(&mut out);
        let st = p.raw_state();
        let mut rate_bytes = [0u8; RATE];
        squeeze_from(&st, &mut rate_bytes);
        assert_ne!(rate_bytes, out);
    }
}
